POST http://localhost:3000/register
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "strongpassword123"
}

###

GET http://localhost:3000/users/67ed5f6b445886d166a8d927

###

POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "strongpassword123"
}

###

POST http://localhost:3000/refresh
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZWQ2N2RlYjMwZTdkYzA0ODk2YzZjYSIsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsImlhdCI6MTc0MzYxMzUyOCwiZXhwIjoxNzQ0MjE4MzI4fQ.wHB-IV7L6EUt_LxfmXZmZKEEJkWnvuMwgyGns-7Bu_U
